[package]
name = "potato-ws"
version = "0.1.0"
authors = ["wisatong <wisa.pow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpotato = { path = "libpotato" }
lazy_static = "1.4.0"
